services:
  postgres:
    image: postgres:18
    
    container_name: postgres_zoomcamp_stage3

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi

    ports:
      - "5434:5432"

    volumes:
      - postgres_data_stage3:/var/lib/postgresql

  ingest:
    build: .
    depends_on:
      - postgres
    command:
      [
        "--user", "root",
        "--password", "root",
        "--host", "postgres",
        "--port", "5432",
        "--db", "ny_taxi",
        "--table_name", "yellow_taxi_data"
      ]

volumes:
  postgres_data_stage3: